const names = 
[{
  "id": 1,
  "first_name": "Khalil",
  "last_name": "Cartlidge",
  "email": "kcartlidge0@ow.ly",
  "gender": "Male"
}, {
  "id": 2,
  "first_name": "Rachele",
  "last_name": "Etherington",
  "email": "retherington1@qq.com",
  "gender": "Female"
}, {
  "id": 3,
  "first_name": "Gibbie",
  "last_name": "Landeg",
  "email": "glandeg2@last.fm",
  "gender": "Male"
}, {
  "id": 4,
  "first_name": "Marci",
  "last_name": "Cleare",
  "email": "mcleare3@nasa.gov",
  "gender": "Female"
}, {
  "id": 5,
  "first_name": "Hagan",
  "last_name": "Padilla",
  "email": "hpadilla4@census.gov",
  "gender": "Male"
}, {
  "id": 6,
  "first_name": "Herminia",
  "last_name": "Adney",
  "email": "hadney5@forbes.com",
  "gender": "Female"
}, {
  "id": 7,
  "first_name": "Archibaldo",
  "last_name": "O'Crotty",
  "email": "aocrotty6@desdev.cn",
  "gender": "Male"
}, {
  "id": 8,
  "first_name": "Correy",
  "last_name": "Kintzel",
  "email": "ckintzel7@unesco.org",
  "gender": "Male"
}, {
  "id": 9,
  "first_name": "Grayce",
  "last_name": "Spellar",
  "email": "gspellar8@jalbum.net",
  "gender": "Female"
}, {
  "id": 10,
  "first_name": "Josias",
  "last_name": "Brunskill",
  "email": "jbrunskill9@over-blog.com",
  "gender": "Male"
}, {
  "id": 11,
  "first_name": "Fanchon",
  "last_name": "Grubbe",
  "email": "fgrubbea@spotify.com",
  "gender": "Female"
}, {
  "id": 12,
  "first_name": "Bertrando",
  "last_name": "Shawe",
  "email": "bshaweb@cocolog-nifty.com",
  "gender": "Male"
}, {
  "id": 13,
  "first_name": "Carmine",
  "last_name": "Eaglesham",
  "email": "ceagleshamc@taobao.com",
  "gender": "Male"
}, {
  "id": 14,
  "first_name": "Ellery",
  "last_name": "Pancoast",
  "email": "epancoastd@nature.com",
  "gender": "Male"
}, {
  "id": 15,
  "first_name": "Shane",
  "last_name": "Laughlin",
  "email": "slaughline@gmpg.org",
  "gender": "Female"
}, {
  "id": 16,
  "first_name": "Vernor",
  "last_name": "Sankey",
  "email": "vsankeyf@hao123.com",
  "gender": "Male"
}, {
  "id": 17,
  "first_name": "Lula",
  "last_name": "Breznovic",
  "email": "lbreznovicg@auda.org.au",
  "gender": "Female"
}, {
  "id": 18,
  "first_name": "Violante",
  "last_name": "Curran",
  "email": "vcurranh@dot.gov",
  "gender": "Female"
}, {
  "id": 19,
  "first_name": "Lucie",
  "last_name": "St. Aubyn",
  "email": "lstaubyni@theglobeandmail.com",
  "gender": "Female"
}, {
  "id": 20,
  "first_name": "Nike",
  "last_name": "Caro",
  "email": "ncaroj@scientificamerican.com",
  "gender": "Female"
}, {
  "id": 21,
  "first_name": "Oren",
  "last_name": "Stathers",
  "email": "ostathersk@upenn.edu",
  "gender": "Male"
}, {
  "id": 22,
  "first_name": "Hillary",
  "last_name": "Haddington",
  "email": "hhaddingtonl@washingtonpost.com",
  "gender": "Male"
}, {
  "id": 23,
  "first_name": "Brok",
  "last_name": "Rees",
  "email": "breesm@squarespace.com",
  "gender": "Male"
}, {
  "id": 24,
  "first_name": "Thea",
  "last_name": "Posen",
  "email": "tposenn@twitpic.com",
  "gender": "Female"
}, {
  "id": 25,
  "first_name": "Munroe",
  "last_name": "Cragell",
  "email": "mcragello@issuu.com",
  "gender": "Male"
}]

export default names;